### ISSUE TITLE
Hi, the include path name need to be fixed

### ISSUE THREAD

**Issue by jiangchuanheglobal** [kedebug/yodb#1]
## I'd like to try your yodb engine, but some src files include path are not correct when I compile. e.g.,

./../yodb/include/yodb/db.h:4:10: fatal error: 'db/comparator.h' file not found
# include "db/comparator.h"

---

Can you modify them to make it a little bit clear. Thx.

**Comment by kedebug** [comment]
I'm sorry for the not detailed specification, but I'm sure you can use `cmake` to solve it.
Try to write your `CMakeLists` file like the test files under `test` fold.
